Vagrant.configure(2) do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", inline: 'echo "cd /vagrant/" >> /home/vagrant/.bashrc'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    # v.gui = true
  end

  config.vm.network :private_network, ip: "10.11.12.14"

  # Bridge for remote access
  config.vm.network "forwarded_port", guest: 3001, host: 3001

  # Public ip for virtual machine
  # config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"

  # Hostname
  # config.vm.hostname "sample-node"

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

    config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.vm.provision :shell, path: "./run.sh", run: "always", privileged: false

end
