---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    document_root: /your_app_name
    apt_file: /etc/apt/sources.list.d/google-chrome.list

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - base
    - database
    - webserver
    - google_chrome
