default: &default
  adapter: mysql2
  username: root
  password:
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: dbname_development

test:
  <<: *default
  database: dbname_test

staging:
  <<: *default
  database: dbname_staging
  pool: 16

production:
  <<: *default
  database: dbname_production
  pool: 16
