---
- name: requirements for installing gems
  apt:
    name={{ item }}
  with_items:
    - build-essential
    - make
    - git
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - libmysqlclient-dev
    - libssl-dev
    - redis-server
    - imagemagick


- name: "Download Ruby 2.1.2"
  get_url: url=http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.gz sha256sum=f22a6447811a81f3c808d1c2a5ce3b5f5f0955c68c9a749182feb425589e6635 dest=/root/ruby-2.1.2.tar.gz
  register: download_ruby

- name: "Unpack Ruby 2.1.2"
  shell: mkdir -p /root/ruby-2.1.2 && tar xzf /root/ruby-2.1.2.tar.gz --strip 1 -C /root/ruby-2.1.2
  when: download_ruby|changed

- name: "Configure, make and make install Ruby 2.1.2"
  shell: cd /root/ruby-2.1.2 && ./configure && make && make install
  when: download_ruby|changed

- name: "Remove build artifacts"
  command: rm -rf /root/ruby-2.1.2
  when: download_ruby|changed

- name: Install bundle
  gem: name=bundler user_install=no

- name: Install all gems
  command: bash -lc "bundle install"
  args:
    chdir: '{{ document_root }}'

- name: Create DB
  command: bash -lc "rake db:create"
  args:
    chdir: '{{ document_root }}'

- shell: mysql -u root dbname_development < /tmp/database_dump.sql
- shell: mysql -u root dbname_test < /tmp/database_dump.sql

#- name: DB Migrate
#  command: bash -lc "rake db:migrate"
#  args:
#    chdir: '{{ document_root }}'
