---
- name: install mysql-server
  apt: name=mysql-server state=present
- name: install mysql-client
  apt: name=mysql-client state=present

  # Copy database dump file to remote host
- copy: src=database_dump.sql dest=/tmp
