---
- name: Requirements for installing gems
  apt:
    name={{ item }}
  with_items:
    - build-essential
    - make
    - git
    - ruby1.9.3
    - ruby-dev
    - rubygems1.9.1
    - irb1.9.1
    - ri1.9.1
    - rdoc1.9.1
    - libmysqlclient-dev
    - libssl-dev
    - libopenssl-ruby1.9.1
    - redis-server
    - imagemagick
    - libsqlite3-dev
    - nodejs

- name: Install bundler
  gem: name=bundler user_install=no

- name: Install rails
  gem: name=rails version=4.1 user_install=no

- name: Install all gems
  become: yes
  become_user: vagrant
  ignore_errors: yes
  command: bash -lc "bundle install"
  args:
    chdir: '{{ document_root }}'

- name: Create DB
  become: yes
  become_user: vagrant
  ignore_errors: yes
  command: bash -lc "bundle exec rake db:create"
  args:
    chdir: '{{ document_root }}'

# Edit this to reflect your project settings
#- shell: mysql -u root db_development < /tmp/database_dump.sql
#  become: yes
#  become_user: vagrant
#  ignore_errors: yes

- name: DB Migrate
  become: yes
  become_user: vagrant
  ignore_errors: yes
  command: bash -lc "bundle exec rake db:migrate"
  args:
    chdir: '{{ document_root }}'
