source 'https://rubygems.org'

gem 'rails', '~> 4.1'
gem 'mysql2', '~> 0.3.16'
gem 'therubyracer', '0.12.2', platforms: :ruby
gem 'acts-as-taggable-on', '~> 3.4'
gem 'autoprefixer-rails', '~> 2.2'
gem 'aws-sdk', '~> 1.50'
gem 'bootstrap-sass', '~> 3.2'
gem 'coffee-rails', '~> 4.0'
gem 'exception_notification', '~> 4.0.1'
gem 'foreman', '~> 0.74'
gem 'haml-rails', '~> 0.5'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails', '~> 3.1'
gem 'kaminari', '~> 0.16.1'
gem 'paperclip', '~> 4.1'
gem 'phrase', '~> 0.4'
gem 'puma', '~> 2.9'
gem 'sass-rails', '~> 4.0.4'
gem 'sdoc', '~> 0.4.0', group: :doc # bundle exec rake doc:rails generates the API under doc/api.
gem 'simple_form', '~> 3.0', github: 'plataformatec/simple_form', ref:  '517a0fcc12937d238fba3192a1b12c83dda9301a'
gem 'workflow', '~> 1.1.0'
gem 'jquery-turbolinks'
gem 'uglifier', '~> 2.5'
gem 'devise', '~> 3.3'
gem 'geocoder', '~> 1.2'
gem 'geoip', '~> 1.4'
gem 'redis-rails', '~> 4.0'
gem 'cancancan', '~> 1.9'
gem 'memoist', '~> 0.10'
gem 'rails_admin', '~> 0.6.3' #, git: 'https://github.com/sferik/rails_admin.git'
gem 'safe_yaml', '~> 1.0' , git: 'https://github.com/dtao/safe_yaml.git', ref: 'c9aa71faca9a3cf17d02cfdf6121505a8a9bcfb7' # needed for rails admin
gem 'ckeditor_rails', git: 'https://github.com/tsechingho/ckeditor-rails', ref: '96c935a44002a732df63e6932b9838de7c6d34ec' # fixes problems in Safari
gem 'roadie-rails', '~> 1.0.3'
gem 'sidekiq', '~> 3.2.6'
gem 'sinatra', '~> 1.4.5' # for sidekiq admin
gem 'momentjs-rails', '~> 2.7', github: 'derekprior/momentjs-rails'
gem 'datetimepicker-rails',
    git: 'https://github.com/zpaulovics/datetimepicker-rails.git',
    submodules: true
gem 'omniauth-facebook', '~> 2.0.0'
gem 'htmlentities', '~> 4.3.2'
gem 'date_validator', '~> 0.7.1'
gem 'sidetiq', '~> 0.6.3'
gem 'google_visualr', '~> 2.4.0'
gem 'spinjs-rails', '~> 1.4'


group :development do
  gem 'i18n-tasks', '~> 0.7.8'
  gem 'better_errors', '~> 2.0.0'
  gem 'byebug', '~> 3.5.0'
  gem 'bullet', '4.14.0'
  gem 'coffee-rails-source-maps', '~> 1.4.0'
  gem 'capistrano-bundler', '~> 1.1.3'
  gem 'capistrano-rails', '~> 1.1'
  gem 'guard', '~> 2.6.1', require: false
  gem 'guard-livereload', '~> 2.3.1', require: false
  gem 'rb-fsevent', '~> 0.9.4', require: false
  gem 'letter_opener', '~> 1.2'
  gem 'metric_fu', '~> 4.11', require: false
  gem 'pry-byebug', '~> 2.0'
  gem 'pry-doc', '~> 0.6', require: false
  gem 'pry-stack_explorer', '~> 0.4'
  gem 'quiet_assets', '~> 1.0.3'
  gem 'roodi', '~> 3.3'
  gem 'spring', '~> 1.1'
  gem 'rack-livereload', '~> 0.3.15'
end

group :test do
  gem 'simplecov', '~> 0.9.1', :require => false
  gem 'capybara', '~> 2.4', require: false
  gem 'faker', '~> 1.4.3'
  gem 'factory_girl_rails', '~> 4.4'
  gem 'spring-commands-rspec', '~> 1.0'
  gem 'rspec-rails', '~> 3.0'
  gem 'rspec-its', '~> 1.0'
  gem 'guard-rspec', '~> 4.3', require: false
  gem 'database_cleaner', '~> 1.3'
  gem 'terminal-notifier-guard', '~> 1.5'
  gem 'selenium-webdriver', '~> 2.43.0'
end

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
